
var arLang = {
  "lang-home": "الرئيسية",
  "lang-about": "عنا",
  "lang-services": "الخدمات",
  "lang-contactus": "تواصل معنا",
  "lang-becomepartner": "انضم كشريك",
  "h-nav-partner": "انضم كشريك",
  "lang-header": "احجز دورك بكبسة زر مع تطبيق دوري",
  "lang-downloadhead": "نزل التطبيق الان",
  "lang-downloadsubhead": "متوفر على متجر جوجل وابل ستور",
  "lang-card2head": "سرعة حجز المواعيد",
  "lang-card2p": "احجز موعدك خلال ثوان ولا تتعب نفسك بانتظار الدور",
  "lang-card3head": "لا تضيع الوقت بالانتظار",
  "lang-card3p": "بدلا من الانتظار على الدور يقوم النظام بتنبيهك عند اقتراب موعد دورك",
  "lang-card4head": "اشغل وقتك بما هو افضل",
  "lang-card4p": "لا مزيد من ضياع الوقت, تطبيق دوري يعطيك الحل الامثل",
  "lang-patnerhead": "كن شريكا في مشروع دوري",
  "lang-partnersubhead": "يمكنك الان ان تكون شريكا لنا في المشروع وستستفيد من العروض الرائعة على التطبيق",
  "lang-partnerp": "هناك ميزات عديدة للشراكة معنا, اضغط الزر الان وابدأ معنا",
  "lang-language": "English",
  "lang-partnerbtn": "انضم كشريك",
  "lang-footerlink1": "الرئيسية",
  "lang-footerlink2": "الرئيسية",
  "lang-footerlink3": "الرئيسية",
  "lang-footerlink4": "الرئيسية",
  "lang-footerlink5": "الرئيسية",
  "lang-footerlink6": "الرئيسية",
  "lang-footerlink7": "الرئيسية",
  "lang-footerlink8": "الرئيسية",
  "lang-footerlink9": "الرئيسية",
  "lang-footerlink10": "الرئيسية",
  "lang-footerlink11": "الرئيسية",
  "lang-footerlink12": "الرئيسية",
  "lang-footerlink13": "الرئيسية",
  "lang-footerlink14": "الرئيسية",
  "lang-footerlink15": "الرئيسية",
  "lang-footerlink16": "الرئيسية",
  "lang-footerlink17": "الرئيسية",
  "lang-footerlink18": "الرئيسية",
  "lang-abouttitle": "من نحن",
  "lang-aboutsubtitle": "تعرف علينا عن قرب",
  "lang-aboutp": "شاركنا تجربة النجاح وكن واحدا من ضمن عشرات الشركات المميزة التي تعمل معنا",
  "lang-teamtitle": "أروع فريق عمل",
  "lang-contacttitle": "راسلنا",
  "lang-contacsubtitle": "نحن دائما مستعدون لسماع اية ملاحظات او استفسارات حول خدماتنا. قم بإرسال رسالة وسنقوم بالرد بأسرع وقت ممكن",
  "lang-contactfrmtitle": "أرسل رسالة",
  "lang-contactname": "الاسم الكامل",
  "lang-contactinfo": "معلومات الاتصال",
  "lang-contactsubject": "الموضوع",
  "lang-contactmsg": "الرسالة",
  "lang-contactsubmitButton": "أرسل",
  "lang-partnertitle": "انضم لنا كشريك",
  "lang-partnersubtitle":"شراكتنا علامة مميزة ونقطة مضيئة في سماء الأعمال",
  "lang-partnerfrmtitle":"انضم الينا الان",
  "lang-partnerfname":"الاسم الأول",
  "lang-partnerlname":"الاسم الأخير",
  "lang-partneremail":"الايميل",
  "lang-partnermobile":"موبايل",
  "lang-partnerbtnsubmit":"أرسل",
  "lang-partnerfeaturestitle": "ميزات أن تكون شريكنا في مشروع دوري",
  "lang-terms": "الشروط والأحكام",
  "lang-privacy": "سياسة الخصوصية"
};

var enLang = {
  "lang-home": "Home",
  "lang-about": "About",
  "lang-services": "Services",
  "lang-contactus": "Contact us",
  "lang-becomepartner": "become a partner",
  "h-nav-partner": "become a partner",
  "lang-header": "Text content to be here inside this area",
  "lang-downloadhead": "Text content to be here inside this",
  "lang-downloadsubhead": "area Text content to be here Text content",
  "lang-card2head": "test header",
  "lang-card2p": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
  "lang-card3head": "test header",
  "lang-card3p": "test data",
  "lang-card4head": "test header",
  "lang-card4p": "test details",
  "lang-patnerhead": "Become a Partner this is section title",
  "lang-partnersubhead": "Lorem ipsum dolor sit amet, consect",
  "lang-partnerp": "Lorem ipsum dolor sit amet, consectetur adipisic",
  "lang-partnerbtn": "Become a partner",
  "lang-language": "العربية",
  "lang-footerlink1": "Home",
  "lang-footerlink2": "Home",
  "lang-footerlink3": "Home",
  "lang-footerlink4": "Home",
  "lang-footerlink5": "Home",
  "lang-footerlink6": "Home",
  "lang-footerlink7": "Home",
  "lang-footerlink8": "Home",
  "lang-footerlink9": "Home",
  "lang-footerlink10": "Home",
  "lang-footerlink11": "Home",
  "lang-footerlink12": "Home",
  "lang-footerlink13": "Home",
  "lang-footerlink14": "Home",
  "lang-footerlink15": "Home",
  "lang-footerlink16": "Home",
  "lang-footerlink17": "Home",
  "lang-footerlink18": "Home",
  "lang-abouttitle": "About Us Page",
  "lang-aboutsubtitle": "Some text about who we are and what we do",
  "lang-aboutp": "Resize the browser window to see that this page is responsive by the way",
  "lang-teamtitle": "The team behind the magic",
  "lang-contacttitle": "Contact Us",
  "lang-contacsubtitle": "We are always ready to answer your mails. If you have a question, inquiry, then please feel free to use the form below to drop us an email",
  "lang-contactfrmtitle": "Drop us a message!",
  "lang-contactname": "Full Name",
  "lang-contactinfo": "Contact info",
  "lang-contactsubject": "Subject",
  "lang-contactmsg": "Message",
  "lang-contactsubmitButton": "Send",
  "lang-partnertitle": "Become our partner",
  "lang-partnersubtitle":"Some text about who we are and what we do",
  "lang-partnerfrmtitle":"Join Us Today!",
  "lang-partnerfname":"First name",
  "lang-partnerlname":"Last name",
  "lang-partneremail":"Email address",
  "lang-partnermobile":"Mobile",
  "lang-partnerbtnsubmit":"Submit",
  "lang-partnerfeaturestitle": "Why to be our partner",
  "lang-terms": "Terms & Conditions",
  "lang-privacy": "Privacy & Cookies Policy"
};
